### ISSUE TITLE
Question Marzban Panel

### ISSUE THREAD

**Issue by hamednaghshinehfard** [dev-ir/speedtest-ban#1]
سلام وقت بخیر 

واسه پنل مرزبان هم اسکریپتی دارید که همین کارو انجام بده ؟

**Comment by dev-ir** [comment]
سلام در این نسخه برای مرزبان ارائه نکردیم 
اما در اپدیت بعدی اسکریپت مرزبان اضافه میشود

**Comment by hamednaghshinehfard** [comment]
با تشکر
