### ISSUE TITLE
پنل مرزبان

### ISSUE THREAD

**Issue by solianon** [dev-ir/speedtest-ban#2]
نمیشه اینو برای پنل مرزبان اپدیت کنید؟
که اونجا هم بشه بلاک کرد اسپید تست هارو؟
🙏🙏🙏

**Comment by dev-ir** [comment]
سلام و درود
به زودی دستیار مرزبان هم منتشر میشود

**Comment by besttrove** [comment]
سلام وقتتون بخیر 
کی منتشر میکنین خیلی منتظر بودم ممنون میشم اطلاع بدید

**Comment by dev-ir** [comment]
متاسفانه به خاطر شرایط مرزبان امکان پذیر نیست .
